### ISSUE TITLE
파일 읽어들이는 방법

### ISSUE THREAD

**Issue by Jiji0405** [Jiji0405/swProject#1]
의논 중 나온 FileInputStream 사용하자는 의견에서 
파일의 내용을 한 줄 씩 읽어들일때 BufferedReader가 적절해 보이는데.. 
의견 부탁드립니다~~!
@YiJinKim

**Comment by yijinKim** [comment]
좋아요.
그럼 BufferedReader, BufferedWriter를 이용해서 파일 입출력을 하는 것으로 할까요?

**Comment by Jiji0405** [comment]
네. 그럼 그렇게 진행하도록 하겠습니다.
