### ISSUE TITLE
파일저장할 공간 이름 설정

### ISSUE THREAD

**Issue by yijinKim** [Jiji0405/swProject#2]
파일 저장할 로컬 저장소 이름은 똑같이 만들어야하지않을까요?
그래야 가계부 파일과 메모 파일도 같이 저장할거같아서요
로컬저장소 이름 sw로 하나요?
의견내주세요~
@Jiji0405 @soosan94

**Comment by Jiji0405** [comment]
좋은 의견인거 같습니다.
그럼 파일 생성할때 경로 설정시 반영하도록 하겠습니다.

**Comment by soosan94** [comment]
앗 이제 봤네요....... 로컬 저장소 이름 swProject로 했는데....

**Comment by yijinKim** [comment]
그냥 해도 상관없을거같긴해요
