### ISSUE TITLE
FileEdit 클래스에서 메뉴 별로 통합시키기

### ISSUE THREAD

**Issue by Jiji0405** [Jiji0405/swProject#3]
가계부나 메모 각각 메뉴에 따라 관리되어지는 파일이나 텍스트 저장 포맷이 다른데
어떻게 코드로 일반화를 시켜서 어느 메뉴에서나 충돌없이 실행될 수 있을까요?
@YiJinKim

**Comment by yijinKim** [comment]
가계부랑 메모랑 각자 파일이 달라서 파일경로를 각각의 변수로 따로 설정해서 선언해주면 되지 않을까요?
memo_file="C:\\Users\\Owner\\sw\\memo.txt";로 money_file = "C:~" 이런식으로요.....
@Jiji0405

**Comment by Jiji0405** [comment]
각자의 파일은 함수의 인수로서 전달되기 때문에 FileEdit 클랫의 함수에서 따로 경로 설정은 필요하지 않을것 같습니다.
각자 수정,저장에서 입력되는 문자열에 포맷을 제시하는 출력문만 메뉴에 따라 구분해주면 될것 같은데요.
FileEdit 클래스의 함수의 int형 변수를 전달하는 인수를 추가하여, 0또는 1을 저장하여 메뉴를 구별한 뒤 함수 내에서 해당 변수를 식별하여 print문(Ex.  ‘수정 내용을 입력하세요. ( 날짜[yyyy-mm-dd]/ 내용/ 가격)’ )을 출력해주는 것이 어떨까요?
피드백 부탁드립니다. @YiJinKim

**Comment by soosan94** [comment]
포맷을 줄려면 메모장인지 가계부인지 인식되어야 하는데 그렇게 할 수 있나요?? 포맷은 각자 클래스에서 사용자에게서 입력 받기 전에 따로 출력하게 끔 하는 것이 좋을 것 같아요.

**Comment by Jiji0405** [comment]
그렇네요. 밖에서 프린트문 호출하고 사용자에게 입력받는 것은 FileEdit class 안에서 하면 훨씬 일반화가 될 수 있을 것 같습니다. @soosan94
