### ISSUE TITLE
혹시 함수만들때 static

### ISSUE THREAD

**Issue by yijinKim** [Jiji0405/swProject#6]
함수만들때 계속 static이 없다고 에러가 떠서
static을 넣어주면 다시 함수가 돌아가더라고요
이문제 해결방법 아는분 없을까요...? @soosan94 @Jiji0405

**Comment by soosan94** [comment]
static 넣어줘야 되는 거 같아요....

**Comment by Jiji0405** [comment]
main에서 함수 호출시 그 함수는 static으로 선언되어야 한다고 알고 있습니다.
